spring:
  profiles:
    active: local
---
## local
spring:
  profiles: local

  # = DATA SOURCE
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # JPA (JpaBaseConfiguration, HibernateJpaAutoConfiguration)
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true

  # H2 Web Console (H2ConsoleProperties)
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true

logging:
  level:
    root: info
    org:
      hibernate:
        SQL: debug # show sql statement
        type:
          descriptor:
            sql: trace # show sql values
